### ISSUE TITLE
null values in example/default schema sections lead to an error

### ISSUE THREAD

**Issue by adrienv1520** [aleksandryackovlev/openapi-mock-express-middleware#8]
### Description on the bug
null values in example/default schema sections lead to an error.

### Context
- Operating System: OSX
- Node Version: 12.15.0
- NPM Version: 6.13.4
- openapi-mock-express-middleware Version: 0.2.5

### Expected Behavior

```json
{
    "name": null,
    "version": null,
    "hostname": "service-checkmail-s1-v5",
    "started_at": "2020-03-25T10:54:05.57Z"
}
```

### Actual Behavior

```json
{
    "code": "unhandled-error",
    "message": "Cannot read property 'generate' of null",
    "stack": "TypeError: Cannot read property 'generate' of null\n    at reduce (/Users/adrien/Desktop/dev/mock/node_modules/json-schema-faker/dist/main.cjs.js:2727:22)\n    at /Users/adrien/Desktop/dev/mock/node_modules/json-schema-faker/dist/main.cjs.js:2829:23\n    at Array.forEach (<anonymous>)\n    at reduce (/Users/adrien/Desktop/dev/mock/node_modules/json-schema-faker/dist/main.cjs.js:2827:24)\n    at /Users/adrien/Desktop/dev/mock/node_modules/json-schema-faker/dist/main.cjs.js:2829:23\n    at Array.forEach (<anonymous>)\n    at reduce (/Users/adrien/Desktop/dev/mock/node_modules/json-schema-faker/dist/main.cjs.js:2827:24)\n    at /Users/adrien/Desktop/dev/mock/node_modules/json-schema-faker/dist/main.cjs.js:2829:23\n    at Array.forEach (<anonymous>)\n    at reduce (/Users/adrien/Desktop/dev/mock/node_modules/json-schema-faker/dist/main.cjs.js:2827:24)"
}
```

### Code

```js
const path = require('path');
const express = require('express');
const mockServer = require('openapi-mock-express-middleware');

const app = express();

app.use(
  '/api',
  mockServer.default({
    file: path.join(__dirname, 'api.yaml'),
    locale: 'en',
    options: {
      alwaysFakeOptionals: true,
      useExamplesValue: true,
    },
  }),
);

app.use((err, req, res, next) => {
  res.status(500).json({
    code: 'unhandled-error',
    message: err.message,
    stack: err.stack,
  })
});

app.listen(2000, () => console.log('Server listening on port 2000'));
```

Yaml schema concerned

```yaml
...
# Index
    index:
      type: object
      properties:
        name:
          type: string
          description: Service name
          readOnly: true
          example: null
        version:
          type: string
          description: Service version
          readOnly: true
          example: null
        hostname:
          type: string
          description: Hostname of this service instance
          readOnly: true
          example: "service-checkmail-s1-v5"
        started_at:
          type: string
          format: date-time
          description: ISO8601 - RFC3339
          readOnly: true
          example: "2020-03-25T10:54:05.570Z"
...
```

### How Do We Reproduce?

Using null values in example or default schema section of the OpenAPI file.

### FIXED

Hi guys, first thanks for this amazing module!! That's exactly what I was looking for!

This issue is happening because of json-schema-faker module. I made a PR that has been merged yesterday if you want to have a look at it:
https://github.com/json-schema-faker/json-schema-faker/pull/594/files

Reinstalling dependencies for users of your module should fix this. Thanks! ;)
